import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "@/shared/navber/page";
import Footer from "@/shared/footer/page";
import { CartProvider } from "./cart/CartProvider";
import { ToastContainer } from "react-toastify";
import Drag from "@/components/Drag";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "practice app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navber />
        <Drag></Drag>
        <ToastContainer />
        <CartProvider> 
          {children}</CartProvider>
        <Footer />
      </body>
    </html>
  );
}
